store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# superadmin, superadmin@superadmin.com, SuperAdmin@8810625561



admin.site.site_header = 'TelaVergeMart'
admin.site.site_title = 'TelaVergeMart'
admin.site.index_title = 'TelaVergeMart'

urlpatterns = [

    path('', include('products.urls')),
    path('recommender/', include('recommender.urls')),
    path('admin/',include('admin_panel.urls')),
    path('super-admin', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User


class Tshirtproperty(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False) 
    slug = AutoSlugField(populate_from='title', unique=True, null=False, default="")

    class Meta:
        abstract = True    

    def __str__(self):
        return self.title
        
class Occassion(Tshirtproperty):
    pass

class Sleeve_type(Tshirtproperty):
    pass

class Neck_type(Tshirtproperty):
    pass

class Ideal_for(Tshirtproperty):
    pass

class brand(Tshirtproperty):
    pass

class color(Tshirtproperty):
    pass

class product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)
    slug = AutoSlugField(populate_from='name', unique=True, null=False, default="")
    desc = models.TextField(null=False)
    discount = models.IntegerField(default=0)
    image1 = models.ImageField(upload_to='products', null=False)
    image2 = models.ImageField(upload_to='products', null=False)
    image3 = models.ImageField(upload_to='products', null=False)
    image4 = models.ImageField(upload_to='products', null=False)
    occassion = models.ForeignKey(Occassion, on_delete=models.CASCADE)
    sleeve = models.ForeignKey(Sleeve_type, on_delete=models.CASCADE)
    neck = models.ForeignKey(Neck_type, on_delete=models.CASCADE)
    ideal = models.ForeignKey(Ideal_for, on_delete=models.CASCADE)
    brand = models.ForeignKey(brand, on_delete=models.CASCADE)
    color = models.ForeignKey(color, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    
class Sizevariant(models.Model):
    id = models.AutoField(primary_key=True)
    SIZES = (
        ('S', "Small"),
        ('M', "Medium"),
        ('L', "Large"),
        ('XL', "Extra Large"),
        ('XXL', "Extra Extra Large"),
    )
    price = models.IntegerField(null=False)
    tshirt = models.ForeignKey(product, on_delete=models.CASCADE)
    size = models.CharField(choices=SIZES, max_length=5)


class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    sizevariant = models.ForeignKey(Sizevariant, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class order(models.Model):
    id = models.AutoField(primary_key=True)
    orderStatus = (
        ('PENDING', "Pending"),
        ('PLACED', "Your Order Is Placed"),
        ('CANCELED', "Your Order Is Canceled"),
        ('PACKED', "Your Order Is Packed"),
        ('SHIPPED', "Your Order Is Ready For Shipping"),
    )
    method = (
        ('COD', "Cod"),
        ('ONLINE', "Online"),
    )
    order_status = models.CharField(max_length=15, choices=orderStatus)
    payment_method = models.CharField(max_length=15, choices=method)
    shipping_address = models.CharField(max_length=150, null = False)
    phone = models.CharField(max_length=10, null = False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.IntegerField(null=False)
    date = models.DateTimeField(null=False, auto_now_add=True)

    def __str__(self):
        return self.order_status


class order_item(models.Model):
    id = models.AutoField(primary_key=True)
    Order = models.ForeignKey(order, on_delete=models.CASCADE)
    tshirt = models.ForeignKey(product, on_delete=models.CASCADE)
    size = models.ForeignKey(Sizevariant, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False)
    price = models.IntegerField(null=False)
    date = models.DateTimeField(null=False, auto_now_add=True)

class Payment(models.Model):
    id = models.AutoField(primary_key=True)
    Order = models.ForeignKey(order, on_delete=models.CASCADE)
    payment_status = models.CharField(max_length=15, default='FAILED')
    date = models.DateTimeField(null=False, auto_now_add=True)
    payment_id = models.CharField(max_length=70)
    payment_request_id = models.CharField(max_length=70, unique=True, null = False)

templates/all.html
{% extends 'base.html' %}
{% block title %}
All Products
{% endblock title %}
{% block body %}
{% load custom_tags %}
{% load static %}

<section class="bg-light py-4">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <h3 class="h3 mb-0">All Products</h3>
      </div>
      <div class="col-md-6 mt-3 mt-md-0">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb justify-content-md-end bg-transparent p-0 m-0">
            <li class="breadcrumb-item"><a class="link-title" href="{% url 'home' %}">Home</a>
            </li>
            <li class="breadcrumb-item"><a class="link-title" href="#">Shop</a></li>
            <li class="breadcrumb-item active text-primary" aria-current="page">All Products</li>
          </ol>
        </nav>
      </div>
    </div>
    <!-- / .row -->
  </div>
  <!-- / .container -->
</section>

<!--hero section end--> 


<!--body content start-->

<div class="page-content">

<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-12 order-lg-1">
        <div class="row mb-4 align-items-center">
          <div class="col-md-5 mb-3 mb-md-0"> <span class="text-dark">Showing 1 to 12 of 30 total</span>
          </div>
        </div>
        <div class="row">
        {% for i in prod %}
          <div class="col-lg-4 col-md-6 mb-5">
            <div class="card product-card card--default rounded-0">
                        <div class="sale-label">{{i.discount}}%</div>
                        <a class="card-img-hover d-block" href="{% url 'product_detail' i.slug %}"> <img class="card-img-back" src="{{i.image1.url}}" alt="..."> <img class="card-img-front" src="{{i.image2.url}}" alt="..."> </a>
                        <div class="card-info">
                          <div class="card-body">
                            <div class="product-title font-w-5"><a class="link-title" href="{% url 'product_detail' i.slug %}">{{i.name|title}}</a> </div>
                            <div class="mt-1"> <span class="product-price text-pink"><del class="text-muted">Rs. {% prices i %}</del>Rs. {% discount i %}</span>
                              <div class="star-rating"><i class="las la-star"></i><i class="las la-star"></i><i class="las la-star"></i><i class="las la-star"></i><i class="las la-star"></i> </div>
                            </div>
                          </div>
                          <div class="card-footer bg-transparent border-0">
                            <div class="product-link d-flex align-items-center justify-content-center">
                              <button class="btn-cart btn btn-pink mx-3" type="button"><i class="las la-shopping-cart mr-1"></i> Add to cart </button>
                            </div>
                          </div>
                        </div>
                      </div>
          </div>
          {% endfor %}
        </div>
        {%	include	"pagination.html"	with	page=products	%}        
      </div>
      <div class="col-lg-3 col-md-12 sidebar mt-8 mt-lg-0">
      <form action="" id="filterform">
        <div>
          <div class="widget widget-categories mb-4 border rounded p-4">
            <h5 class="widget-title mb-3">Brands</h5>
            <select onchange="submitform()" name="prodbrand" class="form-control" id="brands" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in brand %}
              <option
              {% selected_attr request.GET.prodbrand i.slug %}
               value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>
            <h5 class="widget-title mb-3 my-3">Neck Type</h5>
            <select onchange="submitform()" name="neck" class="form-control" id="neck" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in neck %}
              <option {% selected_attr request.GET.neck i.slug %} value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>     
            <h5 class="widget-title mb-3 my-3">Occassion</h5>
            <select onchange="submitform()" name="occ" class="form-control" id="occassion" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in occ %}
              <option {% selected_attr request.GET.occ i.slug %} value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>
             <h5 class="widget-title mb-3 my-3">Sleeve Type</h5>
            <select onchange="submitform()" name="sleeve" class="form-control" id="sleeve" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in sleeve %}
              <option {% selected_attr request.GET.sleeve i.slug %} value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>
             <h5 class="widget-title mb-3 my-3">Ideal</h5>
            <select onchange="submitform()" name="ideal" class="form-control" id="Ideal" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in ideal %}
              <option {% selected_attr request.GET.ideal i.slug %} value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>
             <h5 class="widget-title mb-3 my-3">color</h5>
            <select onchange="submitform()" name="prodcolor" class="form-control" id="color" aria-label="Default select example">
              <option value="">Select</option>
              {% for i in colors %}
              <option {% selected_attr request.GET.prodcolor i.slug %} value="{{i.slug}}">{{i.title|title}}</option>
              {% endfor %}
            </select>
          </div>          
        <a class="btn btn-primary" href="{% url 'all_prod' %}" type="submit">Clear Filters</a>
        </div>
      </form>
      </div>
    </div>
  </div>
</section>
</div>

<script>
function submitform(){
  document.getElementById('filterform').submit()
}
</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

<!-- meta tags -->
<meta charset="utf-8">
<meta name="keywords" content="bootstrap 4, premium, multipurpose, ecommerce, html5, css" />
<meta name="description" content="Telaverge Mart" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Title -->
<title>{% block title %}
{% endblock title %}</title>

<!-- Favicon Icon -->
<link rel="shortcut icon" href="sta images/favicon.png" />

<!-- inject css start -->

<link href="{% static 'css/theme-plugin.css' %}" rel="stylesheet" />
<link href="{% static 'css/theme.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/custom.css' %}" rel="stylesheet" />

<!-- inject css end -->
<style>
{% block style %}
{% endblock style %}
</style>
</head>

<body>

<!-- page wrapper start -->

<div class="page-wrapper"> 
  
  <!-- preloader start -->
  
  <div id="ht-preloader">
    <div class="loader clear-loader"> <img class="img-fluid" src="{% static 'images/loader.gif' %}" alt=""> </div>
  </div>
  
  <!-- preloader end --> 
  
  <!--header start-->
  
  {% include 'header.html' %}
  {% block body %}

  {% endblock body %}
{% include 'footer.html' %}
  <div class="scroll-top"><a class="smoothscroll" href="#top"><i class="las la-angle-up"></i></a></div>

<!--back-to-top end--> 

<!-- inject js start --> 

<script src=" {% static 'js/jquery-3.5.1.min.js' %}"></script> 
<script src=" {% static 'js/popper.min.js' %}"></script> 
<script src=" {% static 'js/bootstrap.min.js' %}"></script> 
<script src=" {% static 'js/owl.carousel.min.js' %}"></script> 
<script src=" {% static 'js/light-slider.js' %}"></script> 
<script src=" {% static 'js/parallax.js' %}"></script> 
<script src=" {% static 'js/magnific-popup.min.js' %}"></script> 
<script src=" {% static 'js/jquery.countdown.min.js' %}"></script> 
<script src=" {% static 'js/jquery.dd.min.js' %}"></script> 
<script src=" {% static 'js/validator.js' %}"></script> 
<script src=" {% static 'js/wow.js' %}"></script> 
<script src=" {% static 'js/theme-script.js' %}"></script> 

</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% block title %}
Checkout
{% endblock title %}
{% load static %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% load custom_tags %}
<div class="page-content">

<section class="checkout-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12">
        <div class="checkout-form box-shadow white-bg">
          <h4 class="mb-4 font-w-6">Billing Details</h4>
          <form action="/checkout/" method='post'>
          {% csrf_token %}
          {{form|crispy}}
          <input class="btn btn-primary btn-sm px-4" type="submit" value="Checkout">
          </form>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 mt-5 mt-lg-0">
        <div class="border bg-light-4 p-3 p-lg-5">
        <div class="mb-7">
          <h6 class="mb-3 font-w-6">Your Order</h6>
          <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Size</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for i in cart %}
    <tr>
      {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
      <td>{{i.size.tshirt.name}}</td>
      <td>{{i.size.quantity}}</td>
      <td>{{i.size.size}}</td>
      <td>Rs. {% sale_price i.size.price i.size.tshirt.discount as total_sale_price %} {% multiply total_sale_price i.size.quantity %}</td>
    </tr>
      {% endfor %}
  </tbody>
</table>
        <div class="mb-7">
          <h6 class="mb-3 font-w-6">Your Total Payable Amount</h6>
<h6>Rs. {{cart|cart_total_price}}</h6>
</div>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

</div>

{% endblock body %}

templates/footer.html
{% load static %}
<section class="bg-pink py-9 position-relative overflow-hidden">
  <div class="container">
    <div class="row justify-content-center text-center mb-1">
      <div class="col-lg-6 col-md-10">
        <div class="mb-4">
          <h2 class="mb-0">Be the first and get weekly updates</h2>
        </div>
        <div class="subscribe-form">
          <form id="mc-form" class="row align-items-center no-gutters mb-3">
            <div class="col">
              <input
                value=""
                name="EMAIL"
                class="email form-control input-2 bg-white"
                id="mc-email"
                placeholder="Email Address"
                required
                type="email"
              />
            </div>
            <div class="col-auto">
              <input
                class="btn dark-btn overflow-auto"
                name="subscribe"
                value="Subscribe"
                type="submit"
              />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<footer class="py-11 bg-dark-1">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-4">
        <a class="footer-logo text-white h2 mb-0" href="index.html">
          <img
            class="img-fluid"
            width="200"
            height="120"
            src="{% static 'images/footer-logo.png' %}"
            alt=""
          />
        </a>
        <p class="my-3 text-muted pr-6">
          E-commerce website with AI recommendation system for TelavergeMart.
        </p>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="la la-facebook"></i
            ></a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="la la-dribbble"></i
            ></a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="la la-instagram"></i
            ></a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="la la-twitter"></i
            ></a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="la la-linkedin"></i
            ></a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted ic-2x" href="#"
              ><i class="lab la-pinterest-p"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-8 mt-6 mt-lg-0">
        <div class="row">
          <div class="col-12 col-sm-4 navbar-white">
            <h6 class="mb-4 text-white font-w-5">Quick Links</h6>
            <ul class="navbar-nav list-unstyled mb-0">
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#">Shipment</a>
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="about-us-1.html"
                  >About</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a
                  class="nav-link text-muted font-w-4"
                  href="shop-grid-left-sidebar.html"
                  >Shop</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="faq.html">Faq</a>
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="blog-card.html"
                  >Blogs</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link text-muted font-w-4" href="contact-us.html"
                  >Contact Us</a
                >
              </li>
            </ul>
          </div>
          <div class="col-12 col-sm-4 mt-6 mt-sm-0 navbar-white">
            <h6 class="mb-4 text-white font-w-5">Information</h6>
            <ul class="navbar-nav list-unstyled mb-0">
              <li class="mb-3 nav-item">
                <a
                  class="nav-link text-muted font-w-4"
                  href="terms-and-conditions.html"
                  >Term Of Service</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a
                  class="nav-link text-muted font-w-4"
                  href="privacy-policy.html"
                  >Privacy Policy</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#">Support</a>
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Orders History</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Your Account</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link text-muted font-w-4" href="#">Suppliers</a>
              </li>
            </ul>
          </div>
          <div class="col-12 col-sm-4 mt-6 mt-sm-0 navbar-white">
            <h6 class="mb-4 text-white font-w-5">Shopping Guide</h6>
            <ul class="navbar-nav list-unstyled mb-0">
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#">Site Map</a>
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Search Terms</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Advanced Search</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Return policy</a
                >
              </li>
              <li class="mb-3 nav-item">
                <a class="nav-link text-muted font-w-4" href="#"
                  >Where is my order?</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link text-muted font-w-4" href="#">Our Story</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row text-muted align-items-center pt-9">
      <div class="col-md-7 font-w-4">
        <small>Desgined and Developed By Sanchit Dang</small>
      </div>
      <div class="col-md-5 text-md-right mt-3 mt-md-0">
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a href="#">
              <img
                class="img-fluid"
                src="{% static 'images/pay-icon/01.png' %}"
                alt=""
              />
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <img
                class="img-fluid"
                src="{% static 'images/pay-icon/02.png' %}"
                alt=""
              />
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <img
                class="img-fluid"
                src="{% static 'images/pay-icon/03.png' %}"
                alt=""
              />
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <img
                class="img-fluid"
                src="{% static 'images/pay-icon/04.png' %}"
                alt=""
              />
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <img
                class="img-fluid"
                src="{% static 'images/pay-icon/05.png' %}"
                alt=""
              />
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% load crispy_forms_tags %}
<!--body content start-->

<div class="page-content">

<!--login start-->

<section class="bg-light register">
  <div class="container">
<div class="row justify-content-center text-center">
  <div class="col-10 col-lg-7 col-md-9 shadow p-6 bg-white">
{% if user.is_authenticated %}
{% comment %} <a href="{% url 'home' %}" class="btn btn-success">Go To Shopping</a> {% endcomment %}
<script>
window.location.href='/'
</script>
{% else %}

   <div class="col-lg-12 col-md-12 p-0">
        <div class="mb-6">
           <h2 class="font-w-6">Login</h2>
        </div>
        </div>
      <div class="col-lg-12 col-md-12 ml-auto mr-auto p-0">
        <div class="register-form text-center">
          <form method="post" action="/userlogin/">
          {% csrf_token %}
            {{form|crispy}}
                <input type="submit" class="btn btn-success" value="Login">
            <div class="row">
              <div class="col-md-12">
                <span class="mt-4 d-block">New Customer ? <a href="{% url 'signup' %}">Register</a></span>
              </div>
          </form>
        </div>
      </div>
    </div>

{% endif %}
    </div>
  </div>
</section>

</div>
{% endblock body %}

templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block style %}
input[type="button"] {
    margin-top: 20px;
}
.node {
    height: 10px;
    width: 10px;
    border-radius: 50%;
    display:inline-block;
    transition: all 1000ms ease;
}

.activated {
    box-shadow: 0px 0px 3px 2px rgba(194, 255, 194, 0.8);
}

.divider {
    height: 40px;
    width: 2px;
    margin-left: 4px;
    transition: all 800ms ease;
}

li p {
    display:inline-block;
    margin-left: 25px;
}

li {
    list-style: none;
    line-height: 1px;
}


.blue { background-color: rgba(82, 165, 255, 1); }
.green{ background-color: rgba(92, 184, 92, 1) }
.red { background-color: rgba(255, 148, 148, 1); }
.grey { background-color: rgba(201, 201, 201, 1); }
{% endblock style %}
{% block body %}

<section class="bg-light py-4">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6">
          <h3 class="h3 mb-0">Orders</h3>
        </div>
        <div class="col-md-6 mt-3 mt-md-0">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-md-end bg-transparent p-0 m-0">
              <li class="breadcrumb-item"><a class="link-title" href="#">Home</a>
              </li>
              <li class="breadcrumb-item"><a class="link-title" href="#">Shop</a></li>
              <li class="breadcrumb-item active text-primary" aria-current="page">Orders</li>
            </ol>
          </nav>
        </div>
      </div>
      <!-- / .row -->
    </div>
    <!-- / .container -->
  </section>

<div class="container">
<div class="row">
<div class="col-lg-12">


    
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Products</th>      
      <th scope="col">Status</th>      
      <th scope="col">Payment Method</th>      
    </tr>
  </thead>
  <tbody>
  {% for i in order %}
    <tr>
      <td>{{i.date|date:"D, d M, Y"}}</td>
      <td>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>S.NO</th>
                                <th></th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for oi in i.order_item_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><img height="60px" src="{{oi.tshirt.image1.url}}" alt="" style="border-radius:50%;"></td>
                                <td>{{oi.tshirt.name}}</td>
                                <td>Rs. {{oi.price}}</td>
                                <td>x {{oi.quantity}} qty </td>
                                <td>{% multiply oi.quantity oi.price as result %} Rs. {{result}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>    
                {% comment %} {% if i.order_status == "PLACED"%}
                <td><span class="badge badge-primary">Your Order Is Placed</span></td>
                {% elif i.order_status == "PACKED" %}
                <td><span class="badge badge-info">Your Order Is Packed</span></td>
                {% elif i.order_status == "SHIPPED" %}
                <td><span class="badge badge-success">Your Order Is Ready For Shipping</span></td>
                {% endif %}
               {% endcomment %}
                 {% if i.order_status == "PLACED"%}
                <td>
                <ul id="progress">
    <li><div class="node green"></div><p><strong> Your Order Is Placed</strong></p></li>
    <li><div class="divider blue"></div></li>
    <li><div class="node grey"></div><p>Your Order Is Packed</p></li>
    <li><div class="divider grey"></div></li>
    <li><div class="node grey"></div><p>Your Order Is Ready For Shipping</p></li>
    {% comment %} <li><div class="divider grey"></div></li> {% endcomment %}
</ul>
                </td>
                {% elif i.order_status == "PACKED"%}
                <td>
                                <ul id="progress">
    <li ><div class="node green"></div><p> <strong> Your Order Is Placed</strong></p></li>
    <li><div class="divider blue"></div></li>
    <li><div class="node green"></div><p><strong>Your Order Is Packed</strong></p></li>
    <li><div class="divider blue"></div></li>
    <li><div class="node grey"></div><p>Your Order Is Ready For Shipping</p></li>
    {% comment %} <li><div class="divider grey"></div></li> {% endcomment %}
</ul>
                </td>
                {% elif i.order_status == "SHIPPED"%}
                <td>
                                <ul id="progress">
    <li><div class="node green"></div><p><strong>Your Order Is Placed</strong></p></li>
    <li><div class="divider blue"></div></li>
    <li><div class="node green"></div><p><strong>Your Order Is Packed</strong></p></li>
    <li><div class="divider blue"></div></li>
    <li><div class="node green"></div><p><strong>Your Order Is Ready For Shipping</strong></p></li>
    {% comment %} <li><div class="divider grey"></div></li> {% endcomment %}
</ul>
                </td>
                {% endif %}
                
                {% if i.payment_method == "ONLINE"%}
                <td><span class="btn btn-sm btn-success disabled">By Card</span></td>  
                {% elif i.payment_method == "COD"%}
                <td><span class="badge badge-success">Cash On Delivery</span></td>                
                {% endif %}
              
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>
</div>
{% endblock body %}

templates/pagination.html
<nav aria-label="Page navigation">
          <ul class="pagination justify-content-end">
            {% if page.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{page.previous_page_number}}">Previous</a>
            </li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="#">{{page.number}}</a>
            </li>
            {% if page.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page.next_page_number}}">Next</a>
            </li>
            {% endif %}
          </ul>
        </nav>